# Generated by Django 5.2.6 on 2025-09-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='상품명')),
                ('description', models.TextField(blank=True, verbose_name='상품 상세 설명')),
                ('author', models.CharField(default='작자 미상', max_length=100, verbose_name='작가')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='출판사')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('stock', models.IntegerField(verbose_name='재고 수량')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='카테고리')),
                ('image_url', models.CharField(default='기본이미지url', max_length=255, verbose_name='책 이미지 url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
