# Generated by Django 5.2.6 on 2025-09-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/product_default.jpg', upload_to='', verbose_name='책 이미지'),
        ),
    ]
