# Generated by Django 5.2.6 on 2025-09-29 04:29

from django.db import migrations, models


def set_default_category(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    # category가 NULL인 데이터는 모두 "소설"로 업데이트
    Product.objects.filter(category__isnull=True).update(category="소설")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RunPython(set_default_category, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(
                choices=[
                    ('소설', '소설'),
                    ('프로그래밍', '프로그래밍'),
                    ('시/에세이', '시/에세이'),
                    ('인문', '인문'),
                    ('가정/육아', '가정/육아'),
                    ('요리', '요리'),
                    ('건강', '건강'),
                    ('취미/실용/스포츠', '취미/실용/스포츠'),
                    ('컴퓨터/IT', '컴퓨터/IT'),
                    ('경제/경영', '경제/경영'),
                    ('자기계발', '자기계발'),
                    ('정치/사회', '정치/사회'),
                    ('역사/문화', '역사/문화'),
                    ('종교', '종교'),
                    ('예술/대중문화', '예술/대중문화'),
                    ('중/고등참고서', '중/고등참고서'),
                    ('기술/공학', '기술/공학'),
                    ('외국어', '외국어'),
                    ('과학', '과학'),
                    ('취업/수험서', '취업/수험서'),
                    ('여행', '여행')
                ],
                max_length=20,
            ),
        ),
    ]
