# Generated by Django 5.2.6 on 2025-09-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('주문 완료', '주문 완료'), ('배송중', '배송중'), ('배송완료', '배송완료')], default='주문 완료', max_length=20),
        ),
    ]
