# Generated by Django 5.2.6 on 2025-09-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_product_remove_orderitem_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
