#version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: /scripts/run.sh
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db         # 여기를 db 컨테이너 이름으로 설정
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SETTINGS_MODULE: config.settings
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app:cached
      - /app/.venv
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media

volumes:
  postgres_data:
