# Generated by Django 5.2.6 on 2025-09-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('대기', '대기'), ('성공', '성공'), ('실패', '실패'), ('취소', '취소')], max_length=10),
        ),
    ]
