# Generated by Django 5.2.6 on 2025-09-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_inquiryreply_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
